"""Reproduce the paper-ready cluster-robust inference table.

The ARR August 2026 manuscript reports a pre-specified 12-comparison family
for each model. The paper-ready table is included in the companion data package
because several rows combine policy outputs generated by different offline
analysis scripts. This script copies that audited table into a requested output
directory and also writes a compact summary.

No LLM/API calls are made.
"""

from __future__ import annotations

import argparse
from pathlib import Path

import pandas as pd


def infer_paper_results(data_root: Path) -> Path:
    """Infer ../paper_results from ../source_data/data when possible."""
    data_root = data_root.resolve()
    for parent in [data_root, *data_root.parents]:
        candidate = parent / "paper_results"
        if candidate.exists():
            return candidate
    if data_root.name == "data" and data_root.parent.name == "source_data":
        return data_root.parent.parent / "paper_results"
    return Path("paper_results")


def markdown_table(df: pd.DataFrame) -> str:
    cols = list(df.columns)
    lines = [
        "| " + " | ".join(cols) + " |",
        "| " + " | ".join(["---"] * len(cols)) + " |",
    ]
    for _, row in df.iterrows():
        vals = []
        for col in cols:
            val = row[col]
            if isinstance(val, float):
                vals.append(f"{val:.4f}")
            else:
                vals.append(str(val))
        lines.append("| " + " | ".join(vals) + " |")
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--data-root", type=Path, default=Path("data"))
    parser.add_argument("--paper-results", type=Path, default=None)
    parser.add_argument("--out", type=Path, default=Path("reproduced/rebuttal_cluster_robust"))
    args = parser.parse_args()

    paper_results = args.paper_results or infer_paper_results(args.data_root)
    in_path = paper_results / "rebuttal_cluster_robust" / "table5_cluster_robust_full_family.csv"
    if not in_path.exists():
        raise FileNotFoundError(
            f"Cannot find {in_path}. Extract the companion data package next to the software package, "
            "or pass --paper-results explicitly."
        )

    args.out.mkdir(parents=True, exist_ok=True)
    df = pd.read_csv(in_path)
    out_path = args.out / "table5_cluster_robust_full_family.csv"
    df.to_csv(out_path, index=False)

    summary_cols = ["model", "comparator", "delta", "ci_lower", "ci_upper", "holm_p", "bh_q"]
    summary = df[summary_cols].copy()
    summary.to_csv(args.out / "query_fe_cluster_robust_summary.csv", index=False)
    lines = [
        "# Multiplicity-Corrected Query-Cluster-Robust Inference",
        "",
        "This table reproduces Appendix Table 5 in the ARR August 2026 manuscript.",
        "Positive deltas favor PromptForest. Holm p-values control the 12-comparison family within each model.",
        "",
        markdown_table(summary),
        "",
    ]
    (args.out / "query_fe_cluster_robust_summary.md").write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {out_path}")


if __name__ == "__main__":
    main()
